### ISSUE TITLE
Spawn vs bed

### ISSUE THREAD

**Issue by Ganjalf-Amsterdoom** [ForgeEssentials/ForgeEssentialsMain#1218]
Hello,

pardon to use issue tracker as a forum, I noticed that if I use /p global spawn here to set default spawn then beds do not work anymore as expected, if you die after using a bed you get spawned at spawn and not at the bed.

Is there a way to spawn in the bed if one was used? I've tried /p global spawn here but does that means I have to setup "a wrapper" to set bed spawn via /p user $player spawn bed or otherwise?

Thank you for your time guys and merry holidays and pardon if I have misunderstood anything.

**Comment by luacs1998** [comment]
Isn't this already implemented? /p global spawn bed or /p group <group> spawn bed?

**Comment by olee** [comment]
No, because then there is no spawn set which can be used if a player has ne bed.
Both settings are needed - whether bed should be used **and** the spawn location.

**Comment by Ganjalf-Amsterdoom** [comment]
Wouldn't make sense to "say/do" that bed is /home, when you die check for home, if is missing or not set then use world spawn...

Is it too much code/implementation change?

**Comment by olee** [comment]
Sorry, but what you are saying is a total different matter. You don't have to care about this issue here as the solution is already planned and just needs to be implemented. Still, thanks for the suggestion.

**Comment by Ganjalf-Amsterdoom** [comment]
No problem and pardon to have bodered.

**Comment by Fogger** [comment]
I have to agree with this.

Spawn should be the fallback when a bed is not available.  It makes no sense for Spawn to take priority.

You may say that it's fine because players can set their own spawn, but players are fundamentally used to setting their home by sleeping in a bed. It's what they expect, and when I tell them they can set their spawn, I get responses like, why do I need a personal `/spawn`, `/home`, `/bed` and `/pwarp`.  It's confusing and makes `/spawn` nothing more than a direct copy of `/home`.

`/spawn` should be a fixed location set by admins, a safe place that is always accessible by all and should only be a target of resurrecting players when no bed exists or a /home has never been set.

In reality, It's better to just forget /spawn exists and create a warp instead. I only gave /spawn to Guests and removed any upward inheritance so normal users wouldn't rage every-time they die.
