### ISSUE TITLE
[REQ] MultiWorld: Importing existing worlds

### ISSUE THREAD

**Issue by Mistercl0ud** [ForgeEssentials/ForgeEssentialsMain#1303]
Could it be possible to had a command to import worlds created outside the multiworld [/mw create ] command ?
Thank you for your time !

**Comment by olee** [comment]
You can import them by hand.
Just create a new multiworld with the command and replace the multiworld-directory with your world-data.
Just be sure that you replace the level.dat of the multiworld you created.

Example:
`/mw create imported`
Replace `./world/FEMultiworld/imported/region` with `./other_world/region`
Replace `./world/FEMultiworld/imported/level.dat` with `./other_world/level.dat`
... and so on and so on....
Just replace all existing files in the multiworld directory like `level.dat` with the ones from your imported world.

**Comment by Mistercl0ud** [comment]
Well I tried to do that but my minecraft crash everytime I use this method.

**Comment by olee** [comment]
Send the crashlog and tell exactly, what you did.

**Comment by Mistercl0ud** [comment]
Sorry I opened a new issue this one was closed. The crash logged is posted there : https://github.com/ForgeEssentials/ForgeEssentialsMain/issues/1304

**Comment by olee** [comment]
No problem. Please continue the conversation here.
Here the error log again: http://pastebin.com/HGzCcMbe

Anyway: 
Try to run the whole thing again without fastcraft installed.

**Comment by Mistercl0ud** [comment]
So, removing Fastcraft and CaveBiomes do stop the crashing of minecraft. However I have another problem when I'm importing a world which was created more recently than the main one : 
1- I created a world with /mw create TestWorld
2- I imported a world that has been created more recently than the first one ( with more mods )
3- When I'm going in TestWorld, many of the blocks have been switched and are not the same

Do you have any idea on how to fix that ?

**Comment by olee** [comment]
oh shit.... yeah.... the problem is the mod-blocklist of forge which manages the relationship 
block-name <--> block-id
When a server starts the first time, it generates this mapping and it only uses the one from the current world - not the multiworld.
We would have to manually load the `level.dat` of the imported world, read the mappings and change all block-ids in the imported world.
Depending on the world-size, this could take quite a while.
It would be interesting to be able to do this, but I have to time to do this now.
This means it's only possible to import worlds which started with the same mods, or you need to remove all mod-blocks from the imported world.

**Comment by Mistercl0ud** [comment]
Thank you for your time and explanation ! I'm guessing those datas are the ones inside : 
level.dat/FML/Itemdata ( around 3800 entries )

**Comment by olee** [comment]
Yes, exactly.

**Comment by luacs1998** [comment]
FML has a mechanism for fixing block/item IDs - we just need to hook into it.

**Comment by olee** [comment]
This code is (nearly) useless for this case, because we cannot just remap IDs, but instead need to go through the whole save and replace the IDs in the world-data.
