### ISSUE TITLE
Creating modules

### ISSUE THREAD

**Issue by a2937** [ForgeEssentials/ForgeEssentialsMain#1331]
I've cloned the repository and managed to get Eclipse without any errors with your project. I want to try to port two of my favorite Bukkit plugins as modules, but am not quite sure of how. How did you get past the need for an OfflinePlayer class, and even tell if the player has permission for commands? Thanks for  answering this question.

**Comment by luacs1998** [comment]
I really don't want to have to walk you through Forge modding. Your best bet would be to get on the minecraftforge irc (irc.esper.net #minecraftforge).

For the record, you'd be better off being a regular FML @mod instead of being a FE module. FE modules are just an internal hackaround to prevent the main mod from being too bloated.
