### ISSUE TITLE
Fastcraft and Fe don't get along together in same enviroment.

### ISSUE THREAD

**Issue by Flukethoughts** [ForgeEssentials/ForgeEssentialsMain#1351]
FE 459
Fastcraft 1.19
Modpack magitechworld technic

**Comment by luacs1998** [comment]
We patch things, they patch things too. You know the drill, we need logs.

**Comment by Flukethoughts** [comment]
trust me if i could provide u a log with better information i would but the information it spits out is simplistic
Enjoy though
http://pastebin.com/EjNp1dY4

**Comment by luacs1998** [comment]
Seems like their ASM is erroring out... pinging @sfplayer1

**Comment by sfPlayer1** [comment]
Hmm interesting. What is ForgeEssentials editing in EntityPlayerMP? The error means that the fc injector found 3 location matches instead of the expected 1.

I also need the CLASSLOADER_TEMP/net/minecraft/entity/player/EntityPlayerMP.class from the same setup without FastCraft installed. The server needs the additional parameters -Dlegacy.debugClassLoading=true -Dlegacy.debugClassLoadingSave=true to generate said file. Don't forget to disable it again afterwards.

**Comment by FiveEYZ** [comment]
im generating same error on my FTB Infinity server, here is the file you are requesting. https://drive.google.com/open?id=0B47wGOooeWGIV0pQZTZoQkxmZDA&authuser=0

**Comment by sfPlayer1** [comment]
The file isn't publicly accessible.

**Comment by FiveEYZ** [comment]
should be public now

**Comment by sfPlayer1** [comment]
The real issue is in the mixin library ForgeEssentials pulls in.

There's an extra transformer invocation in:
at org.spongepowered.asm.mixin.transformer.TreeInfo.applyTransformers(TreeInfo.java:147)

Apparently it also causes LaunchClassLoader to drop the class, loading it again later, which whould be the 3rd invocation Fastcraft counted.

That's invalid since the class loader prevents multiple invocations. Doing so regardless imposes extra requirements on the IClassTransformer implementations, which aren't necessarily met.

**Comment by micmou** [comment]
Same bug experienced on custom RR Server log is below no crash report
http://pastebin.com/TmjPBnSZ

**Comment by sfPlayer1** [comment]
You can potentially work around it by specifying the extra java parameter -Dfastcraft.asm.permissive (before -jar).

**Comment by micmou** [comment]
Seems to be working so far thanks I imagine it is pretty dirty to bypass it

**Comment by DPxKnightxZero** [comment]
Confirmed fix :D

**Comment by FiveEYZ** [comment]
think he meant "dirty to bypass it" because its a server issue and not client.

**Comment by DPxKnightxZero** [comment]
Fixed
