### ISSUE TITLE
Bug Denying Creatures To Spawn Doesn't Work

### ISSUE THREAD

**Issue by DPxKnightxZero** [ForgeEssentials/ForgeEssentialsMain#1357]
I tried to setup a shop zone where creatures could not naturally spawn and it didn't work at all. They still spawned despite not being allowed.

**Comment by helinus** [comment]
What permnodes did you deny and what creatures are still spawning?
Doublecheck you applied the perms to the correct zone.

**Comment by DPxKnightxZero** [comment]
deny fe.protection.mobSpawn.natural.* this is what I set as the world guard

**Comment by olee** [comment]
1. Did you ensure you correctly set up the zone?  
Get inside it and run `/p list zones` to check if it's listed.
2. The correct command to deny spawning of mobs should be  
`/p global zone XYZ deny fe.protection.mobSpawn.natural.*`

**Comment by DPxKnightxZero** [comment]
Yeah but I can try again with the new version. Also is there a way to deny mobs with the hostile flag to spawn only? I want to add peaceful dimensions and I don't see that as a thing anywhere.

**Comment by olee** [comment]
I think we could add these as new permissions.
````
fe.protection.mobSpawn.natural.hostile
fe.protection.mobSpawn.natural.neutral
fe.protection.mobSpawn.forced.hostile
fe.protection.mobSpawn.forced.neutral
````

**Comment by DPxKnightxZero** [comment]
That would be seriously EPIC!

**Comment by luacs1998** [comment]
Should already be implemented.

**Comment by DPxKnightxZero** [comment]
I didn't notice any tutorial on usage so I assumed it didn't exist.

**Comment by olee** [comment]
@luacs1998 Hostile / not hostile permissions do not exist yet.
At least I didn't find any in the permission list file.

**Comment by luacs1998** [comment]
I was referring to per-zone game modes/difficulty. Sorry for being unclear.

**Comment by DPxKnightxZero** [comment]
Question if I do the per zone modes/difficulty does it affect individual players or if someone enters a {PEACEFUL} zone does it broadcast the server?

**Comment by DPxKnightxZero** [comment]
Allow deny creature spawns still doesn't work. It literally stops nothing.

**Comment by olee** [comment]
1. Show us the commands you used to set permissions or the contents of the perm-files.
2. The following command should disable spawning of any mobs in a zone named `XYZ`:  
  `/p global zone XYZ deny fe.protection.mobSpawn.natural.*`

**Comment by DPxKnightxZero** [comment]
I copy pasted your command and set

/p global zone 36 deny fe.protection.mobSpawn.natural.*

**Comment by olee** [comment]
And it does not work?

**Comment by DPxKnightxZero** [comment]
It does not work. I don't know if it lacks mob compatibility but the mobs are mobs right?

**Comment by olee** [comment]
As you can see, it works.
The left side under the roof is an area with `fe.protection.mobspawn.natural.* = false`.
It might be because you used `mobSpawn` instead of `mobspawn`.
You can always use TAB completion to check permissions.

![spawn_permissions](https://cloud.githubusercontent.com/assets/6547794/6979088/064338d6-da19-11e4-8de7-7cd590b422d1.png)

**Comment by DPxKnightxZero** [comment]
Can you please run the same test with lycanites mobs and mca

**Comment by olee** [comment]
Did you first try `fe.protection.mobspawn.natural.*` instead of `fe.protection.mobSpawn.natural.*` ?
That should be the reason it didn't work.
It would take me a lot of time (that I currently don't really have yet) to test it especially with some other mods - even though I'm pretty sure it does work.

Also you can try the following:
- Go into the zone where you want to have mob spawning disabled
- Run `/p test fe.protection.mobspawn.natural`
- If it does not show `false`, you propably did not set the permissions correctly  
  This is something that even happens to me regulary.

**Comment by DPxKnightxZero** [comment]
yes and it didn't work ... I promise I tried a few hundered things even seeting point a: all the way to bedrock ... and point B to the sky. 100 by 100 chunks.

**Comment by olee** [comment]
So what was the result of `/p test fe.protection.mobspawn.natural`?

**Comment by olee** [comment]
See #1390 - try to deny `fe.protection.mobspawn.*` and see if this works.
Also run the `/p test fe.protection.mobspawn.natural` command to check you didn't do anything wrong.
