### ISSUE TITLE
Infinite Inventory Death Chest Crash

### ISSUE THREAD

**Issue by DPxKnightxZero** [ForgeEssentials/ForgeEssentialsMain#1384]
Alright so I have a mod called inifinite inventories but when I try to open the death chest it crashed the game please not when I tested this I was using release 474 
````
---- Minecraft Crash Report ----
java.lang.IndexOutOfBoundsException: Index: 36, Size: 36
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at net.minecraft.inventory.Container.func_75139_a(SourceFile:104)
	at net.minecraft.inventory.Container.func_75131_a(SourceFile:390)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147241_a(NetHandlerPlayClient.java:1057)
	at net.minecraft.network.play.server.S30PacketWindowItems.func_148833_a(SourceFile:49)
	at net.minecraft.network.play.server.S30PacketWindowItems.func_148833_a(SourceFile:11)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1590)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by olee** [comment]
It might be that *infinite inventories* patches containers in some way and deathchests are not covered by this patch (or something similar).
This is a bug by infinite inventories and not us, so you should open a ticket on their bug tracker, or try to get the developer to take a look at the issue here.

**Comment by DPxKnightxZero** [comment]
Okay so I am working with the three modders that use death chests ... Gravestones Mod Creator, You Guys, and The Creator of the twilight forest the reason game crashes is because the death chest in your mod was never configured to add properties which modify the how many death items are stored. Well I have infinite inventory set to allow please exactly 270 or x10 the max vanilla inventory slots. When a play accesses their forge essentails death chest the client tells the server player has 60 slots currently open death chests goes 'um no you can only have 40" and the infinite inventory talks to the client and player saying "alright dude the chest is drunk lets bail."

**Comment by olee** [comment]
So did the client or the server crash?

**Comment by DPxKnightxZero** [comment]
Client.

**Comment by DPxKnightxZero** [comment]
This is how the gravestone mod creator was able to fix it.

Funwayguy commented 13 hours ago

The issue is that your inventory is using a single 'byte' to define the slot IDs in this set of loops:
https://github.com/NightKosh/GraveStone-mod/blob/master/src/main/java/gravestone/tileentity/GSGraveStoneItems.java#L191

This causes the byte to top out at slot 127 then roll around to -127 causing an IndexOutOfBoundsException. To fix this you simply need to use integers instead of bytes.

**Comment by luacs1998** [comment]
Give me a link to the issue you filed on their side - I'd like to have a chat with them.

**Comment by DPxKnightxZero** [comment]
Here is his thing

https://github.com/Funwayguy/InfiniteInvo/issues

**Comment by Funwayguy** [comment]
Normally InfiniteInvo is fine with automatically handling the inventories server side and client side and accounting for that but it appears the InventoryGrave size is trying to use the players inventory's size as the size for the chest it's claiming to be. Whenever a mod changes this size and it no longer equals 36 (the size of a chest), boom bugs occur. In this case the player's inventory is now well above 36 because of InifniteInvo and therefore more than a chest can hold. Unfortunately because this mod is solely server-side and cannot create any such inventory that could hold an infinite amount of items my only suggestion is to somehow cache all the items that don't fit in memory until the grave has space for them to be added.

**Comment by Funwayguy** [comment]
@DPxKnightxZero For the record, the bug with the GraveStone mod is completely different from this one so please don't think that because a solution worked for one person that it's going to fix everything else even if the mods are similar in functionality. Issues need to be solved on a case by case bases and there is no magical fix for all of them.

**Comment by DPxKnightxZero** [comment]
Roger, next time I will make sure to check and make sure with you.

**Comment by olee** [comment]
@Funwayguy 
Thanks for the info.
I will investigate this a bit more and I think I already have a solution for this problem.

**Comment by olee** [comment]
Please try again with latest version.

**Comment by luacs1998** [comment]
Fixed? Closing, reopen if still an issue.
