### ISSUE TITLE
Time controlled permissions (Allow users to enter zones only at certain times of day)

### ISSUE THREAD

**Issue by DPxKnightxZero** [ForgeEssentials/ForgeEssentialsMain#1395]
I had a unique idea ... is there a way to deny my players access to a certain location using /p group _ALL_ zone X deny fe.protection.interact* timevalue = 1200-0000

**Comment by olee** [comment]
Would be very interesting to do this.
I will try to write some kind of scheduler that can change permissions based on the current time.

**Comment by DPxKnightxZero** [comment]
Thank you very much for your efforts. Um sorry to bother you I think you should check this out. https://github.com/ForgeEssentials/ForgeEssentialsMain/issues/1422

**Comment by olee** [comment]
Halfway done.

You can define permission schedules currently by configuring them in
`<world-dir>/FEData/json/PermissionSchedule/<schedule-name>.json`.

Time is measured as seconds (`isRealTime = true`) or in minecraft ticks (`isRealTime = false`).

If `isDelay = false`, the times are always absolute values since midnight (real / minecraft).
The permissions always start with the ON state on midnight.
Example:
```
isRealTime = true
isDelay = false
times[0] = 28800
times[1] = 57600
```
This will turn the permissions ON from midnight until 8:00, OFF until 16:00 and again ON until midnight.

If `isDelay = true` makes the times not absolute, but turns them into delays instead.
Example:
```
isRealTime = true
isDelay = true
times[0] = 5
times[1] = 10
```
This will repeatedly turn the permissions to ON for 5 seconds and then to OFF for 10 seconds.


Full example:
````
{
  "isRealTime": true,
  "isDelay": false,
  "zoneId": 1,
  "group": "_ALL_",
  "onMessage": "Turned permissions ON",
  "offMessage": "Turned permissions OFF",
  "times": [
    9960,
    10020
  ],
  "permissions": {
    "some.test.permission": {
      "on": "true",
      "off": "false"
    },
    "some.test.property": {
      "on": "10",
      "off": "70"
    }
  }
}
````

**Comment by olee** [comment]
For now we will not make a command for this as it is too much work for a rarely used feature.
FE automatically generates a sample that can be copied and modified in the data directory.
That should be enough for players to set this up.

All that is left is to set up a wiki entry.

**Comment by olee** [comment]
Done

**Comment by DPxKnightxZero** [comment]
Question; so in the json how would I define the zone where the schedule takes affect?
