### ISSUE TITLE
Weird random desyncs, falling through world

### ISSUE THREAD

**Issue by luacs1998** [ForgeEssentials/ForgeEssentialsMain#1396]
https://github.com/MinecraftForge/MinecraftForge/issues/1788

Continue here.

**Comment by groveham** [comment]
I'm also having this issue. The linked issue above seems to be closed, I already have the FE Auth Module disabled. My server does not lag, everything runs fine. This has only started since we changed from ServerTools to ForgeEssentials.
Players keep falling through the world when spawning or doing /home. I've removed FE and re-added ServerTools and this solved the issue but I'd rather use FE as it's a much better mod. 

I've checked the logs and there seems to be no reasons for this at all. No errors or any other information.

**Comment by luacs1998** [comment]
Yes, the linked issue was closed as it was in the Forge repo and it's not a Forge issue.

Try setting max-players in server.properties to 20?

**Comment by olee** [comment]
Try again with latest build.
It might be fixed now.

**Comment by olee** [comment]
Can I close this? It might have been an issue with the bed respawn.

**Comment by groveham** [comment]
I'm using FE 1.4.0-beta6 Server and still having the issue, which build do you think it's fixed on?

**Comment by olee** [comment]
Did you get your build from http://ci.forgeessentials.com/job/ForgeEssentials/ ?

**Comment by groveham** [comment]
I got mine from http://minecraft.curseforge.com/mc-mods/74735-forge-essentials-74735

Would you recommend getting it from http://ci.forgeessentials.com/job/ForgeEssentials/ ?

**Comment by olee** [comment]
Yes, always.

**Comment by groveham** [comment]
OK downloading and testing for this issue now, will let you know.

**Comment by luacs1998** [comment]
No news in a week, so I will assume it's been resolved.

If this happens again, make another issue.
