### ISSUE TITLE
[Suggestions]

### ISSUE THREAD

**Issue by micmou** [ForgeEssentials/ForgeEssentialsMain#1499]
Some Things that I had a thought about.

Maybe a permissions bridge with the current cauldron to allow it to handle Perms
https://prok.pw/git/prototik/kcauldron

And what is the compatibility state of mytown 2 as it has its own thing

Basically what I am getting at is it is a B*** to manage three different permission sets per player or group

**Comment by evernife** [comment]
Yeash, kcauldron will really help, but they says this si just for forge, and this is why its called "FORGEessentials" :c

**Comment by dariusc93** [comment]
@micmou FE, afaik doesnt support cauldron/spigot/bukkit and probably never will because of some of the things that went on last year. Secondly, cauldron creates permission nodes for the commands being registered so that is probably why mytown2 works and there is another set if permissions node for forgeessentials. If you dont want to manage multiple systems, you could either

A) Use one system and remove the others 
B) Have a plugin to use vault to "bridge" the permission nodes between FE and spigot (this is what mytown did with forgeperms)
C) Get use to different systems.

**Comment by jburrows82** [comment]
Use Essentials for Cauldron. If you're using vanilla forge, use Forge Essentials. There is no practical sense in using a mod when you can use the plugin system.

**Comment by evernife** [comment]
Essentials plugins dont have a nice system like FE, and cant block items :c

**Comment by olee** [comment]
Well there's not much left for me to say...
This is **not** *Cauldron*Essentials, but **ForgeEssentials**.

Also FE's permission system is so different and powerful, that it would probably be better you use only this one.

If it's about compatibility with other mods however, I don't mind helping you out.

**Comment by micmou** [comment]
Hmm well I have no java Experience a bridge does sound feasible the issue is that It all 3 mods listed have bits and bobs that work well MyTown2 Is badass for a Grief Prevention Plugin
and forge essentials handles things better.

It would be nice to have a forge essentials bridge to cauldron to allow something like PEX to distribute permissions for FE commands. or maybe having FE pull the commands registered inside of cauldron to the FE Handler and allowing FE with that gorgeous remote client to handle it. Which would now that I think about it be preferable. I think it is better to make yourself compatible rather than shooting down the idea as a whole.

**Comment by olee** [comment]
Now this sounds a lot better.

>  ...to allow something like PEX to distribute permissions for FE commands.
What exactly do you mean with that?

> ...pull the commands registered inside of cauldron to the FE Handler
If the commands are registered as Minecraft commands, you should be able to control the commands with FE permissions. I don't know how Cauldron commands and permissions are designed even in the slightest bit so I cannot tell any more.

> MyTown2 Is badass for a Grief Prevention Plugin
Well I also saw that it's quite powerful, but to be honest, you can do even more with FE permissions. The problem is just that users do not have much control over it yet. Only by using plots, users are able to configure at least a bit of the permissions in their own areas. However we intend to improve FE / plots a lot and make it more powerful than MyTown.

**Comment by evernife** [comment]
Being honest, MyTown is working too slow (I think that have only one programmer), lots of bugs; In the way FE is working it will be really more effective than the MyTown.

But, as you mentioned "Grief Prevention", the plot system could "copy" their method, i would have said this before, but someone (I dont remmeber who) said to me to wait till the plot system were done.

My sugestion is use less commands as possible, try to make the plots automaticly, the "Grief Prevention" uses simple a golden shovel and a chest, this could be implemented, players have a few problems with lots of commands.

**Comment by evernife** [comment]
***********************************JUSTA SAYING***********************************
(i am talking with the actual kcauldron manager, i asked him to "do" something about the ForgeEssentials, i dont have true hopes that he will listen me, but, there is no problem to ask... maybe is more easy to "fix" this problem by his side, and by FE)
*********************************************************************************************************

**Comment by micmou** [comment]
Hmm i just found and read the forum. I will post there as well.

**Comment by luacs1998** [comment]
Still, @evernife 

FE has an environment checker that is designed to fail the load if you're running FE on Cauldron or any cauldron derivative. There is an advanced-user switch to disable this, but I don't really recommend using it, and I will not offer support for anyone trying to do so.

This is from prior experience where there have been people pestering blood and me about problems with FE and cauldron. We decided that maintaining an incompatibility is the way to go.
