### ISSUE TITLE
Inexact location with /locate

### ISSUE THREAD

**Issue by Pyeroh** [ForgeEssentials/ForgeEssentialsMain#1505]
When the locate command is performed on a player on positive coordinates, it returns correct coordinates, but when it's performed and the player is on negative coordinates (x/z, not y), the result is increased by one.

Example : 
My real location : -235 65 250
Returned by /locate : -234 65 250

Apparently, that's because it returns the coordinate value without decimals, instead of what's between parenthesis on F3 menu.

It can also be noticed on 0 0 (when you go negative, on the first block after 0 0, it doesn't increase the value)

**Comment by RlonRyan** [comment]
This appears to be a rounding issue...
A check in the code shows this to be true.
<code>(int) player.posX<\code>
This is a poor typecast, which is how the rounding is done. The default of the typecast is to always round down to the nearest integer in the direction of zero, so that is why you see the higher coordinate below zero.

I will submit a pr to fix this.

**Comment by RlonRyan** [comment]
@Pyeroh How consistent is this issue? And how did you round the actual coordinates?

**Comment by Pyeroh** [comment]
![2015-05-20_13 42 49](https://cloud.githubusercontent.com/assets/5567857/7718048/bf0c0dc8-fef6-11e4-8f5e-2c73aabe7642.png)
No problem with this position, I teleported myself on 0 65 0.

![2015-05-20_13 46 30](https://cloud.githubusercontent.com/assets/5567857/7718060/e7a28bcc-fef6-11e4-91a4-7146dfa27790.png)
But here, I teleported on -1 65 0, and I'm located by FE on 0 65 0...
