### ISSUE TITLE
world border fill didn't generate blocks in -z space

### ISSUE THREAD

**Issue by necanthrope** [ForgeEssentials/ForgeEssentialsMain#1508]
Hi :)  I have been playing with world border on my server, which is running with FE version 1.4.0 beta 2 server core.  I enabled the border, set up the radius at 10,000 blocks, set the shape to square, and kicked off the filler.

When I went back this morning, it finished without errors about 7 hours later.  However, when I loaded the resulting world in MCEdit to confirm that it generated, I discovered that only half of that space existed in the world files.  It had generated a rectangle starting at Z=0 and stretching to Z=+10k, and stretching between X=-10k and X=+10k. i.e., only half of the specified chunks were created.

Do I have to re-run the filler with a negative radius value to get it to generate chunks in negative Z space?

**Comment by necanthrope** [comment]
Did I file this in the wrong repo?

**Comment by olee** [comment]
Not really, but we have a lot of important issues / feature requests to take care of in FE and currently it is only me that is actively programming on FE.
Because of that I need to prioritize some issues over others.
That is why I don't have the time to look after this issue yet and need to check it sometime else.

I am sorry for that but for now you need to look for other ways to populate your world.
(Make yourself and some friends fly around the world? Use another mod which has this feature?)

**Comment by necanthrope** [comment]
Ah, ok.  That's cool, thank you for answering. :)  We're considering writing a script that teleports an op around the world in grid formation.

**Comment by olee** [comment]
Continuing in #1513
