### ISSUE TITLE
Censor list is easily bypassed.

### ISSUE THREAD

**Issue by TimB1087** [ForgeEssentials/ForgeEssentialsMain#1520]
Players can easily bypass censored words, simply by adding a letter to the word. So, if I were to censor damn, a player could just type damnu, damndamn, etc, to bypass the censor.

Seems that there should be some improvement to the list to have 'smarter' detection to prevent censoring actual words like ASSume, and bASS, while still being able to properly censor obvious attempts at bypassing. Perhaps incorporate a dictionary check and if it's an actual word, not censor it?

Another approach is to allow wild cards. So, if I add to the censor list BLAH, 'BLAH, and BLAH' (' = asterisk), then something like aBLAH would get censored, but aaBLAH would not.

**Comment by olee** [comment]
We could allow regex for banned words...
Marking as request but I don't know when we will add this...

OT: Then again I think it's a pretty useless feature anyway because trying to control what players chat is pointless. If they want to they are going to find a way to write it and if you don't want that on your server, you will have to kick / ban players like these anyway (e.g. who wants to play with idiots that you need a censor list anyway?).

**Comment by olee** [comment]
@TimB1087 you might also want to just try out other mods like this one: http://www.curse.com/mc-mods/minecraft/227785-safechat
Just stumbled over it today...

**Comment by olee** [comment]
All words filtered by censor use regex.
However by default they are surrounded by word boundary anchors `\b`.
Once #1532 is merged, you can use a `!` in front of a censor word, to disable these word boundary checks.

Example:
Censor word `shit` will be turned into the regex `\bshit\b`.
Censor word `!shit` will be turned into the regex `shit`

**Comment by olee** [comment]
@TimB1087 tip: Use filters like `fuck.*` for example to filter all words beginning with `fuck`.
