### ISSUE TITLE
[Request]-Up to date tutorial using Multiworld

### ISSUE THREAD

**Issue by DPxKnightxZero** [ForgeEssentials/ForgeEssentialsMain#1553]
I am trying to run some tests and I have a few worlds that run mods and my players don't like losing all the things they create I heard multiworld is used specifically to fix such an issue is it possible to keep old worlds and make multiworld portals and link them from point a to b? If so how do I configure the realms and how do I make and link a portal to those realms?

**Comment by olee** [comment]
Multiworlds suffer from the same problems of mods changing so that will not protect you from loosing stuff if you remove mods etc.
The wiki for multiworld is here https://github.com/ForgeEssentials/ForgeEssentialsMain/wiki/Multiworld
You can also create portals with the `/portal` command:
- Select a portal frame with WE wand
- Move to the target location where you want the portal to teleport to
- `/portal create <name>`

**Comment by olee** [comment]
Closing this in regards to #1529
If you still have multiworld specific questions, you can still ask them in this issue or on IRC
