### ISSUE TITLE
Permissions applying to server console?

### ISSUE THREAD

**Issue by thisischrys** [ForgeEssentials/ForgeEssentialsMain#1603]
I setup permissions as in the tutorial, then removed the teleport permission from members.
However now I also can't tp from the server console.
Is the server console treated as a player? If so what is it's name so I can give it all permissions?

**Comment by luacs1998** [comment]
What happens when you try it?

**Comment by olee** [comment]
The server console should always have full permissions (in fact there is no way to check permissions for it).

**Comment by thisischrys** [comment]
"You are not allowed to teleport from here."
Just trying tp player1 player2

**Comment by olee** [comment]
That's because player1 is not allowed to be teleported at all from his current location.
That is part of the teleportation permissions. You probably denied it by denying some parent permission. See [PermissionList.txt](https://github.com/ForgeEssentials/ForgeEssentialsMain/wiki/PermissionList.txt) which will tell about these two permissions:
```sh
fe.teleport.from   # (default: true) Allow being teleported from a certain location / dimension
fe.teleport.to     # (default: true) Allow being teleported to a certain location / dimension
```
