### ISSUE TITLE
Unable to change autobackup location

### ISSUE THREAD

**Issue by AnrDaemon** [ForgeEssentials/ForgeEssentialsMain#1636]
FE 1.4.0 release
MC 1.7.10
Forge 1448
The newly created Backups.cfg no longer reference `S:backupsDir`, adding that parameter doesn't do anything. Location of automatic backups not changed.

**Comment by olee** [comment]
How about symlinking the backup directory.
This is normally easier to do...

**Comment by AnrDaemon** [comment]
I may go that route, but honestly, I prefer solutions to workarounds.
If I go with symlink, I'd have to remember to recreate it every time I reinstate the instance from a full backup.

**Comment by olee** [comment]
Otherwise, when the server is setup somewhere else with same config, one would have to remember to change the backup dir, too. So I don't really know if this is useful (also - how often do you think you are going to setup the same server somewhere else? :smile).
But if you say you think it's needed, we can add it.

**Comment by AnrDaemon** [comment]
Backup directory is (was) specified relative to server root.
I did not intend to change it much from that.

**Comment by olee** [comment]
Ah that's what you actually want.
We might think about moving config files to `config/ForgeEssentials/` then...
@luacs1998 what do you think? I think it's better that way, too.

**Comment by luacs1998** [comment]
Personally, it's not something I want to do now for 1.7.10. 1.8 is another question though, since everyone will be resetting worlds and nuking servers we might consider it,

Had you asked me 2 years ago I wouldn't have any problems with it (and in fact 2 years ago I tried ti have it put in but ya)

**Comment by AnrDaemon** [comment]
I could, but tar is very picky on that part.
And wrapping every archivation line in "find x -y \*.z | tar --from-file=-" is the least entertainign experience.

**Comment by olee** [comment]
Then don't backup it.
You don't even need to.
All the data in ForgeEssentials directory is not necessary to backup.
Only maybe the playerlogger DB and you can change the location of that one.

**Comment by AnrDaemon** [comment]
Does that mean that the entire directory will me removed in a future version?

**Comment by olee** [comment]
If you mean the ForgeEssentials directory, no. Things will stay as they are and we *might* add a feature to allow placing config files *optionally* in `./config/` instead.

As for backup path adding such an option has pretty much no benefits and can be achieved by just using symlinks.

**Comment by AnrDaemon** [comment]
Then why you said that there's nothing to backup? From your words I concluded that this directory is not used by the mod and can be safely deleted.

**Comment by olee** [comment]
I said "not necessary to backup" which is not equal to "can be deleted".
It just means that there is no danger of this data corrupting / changing in any way when the server runs. The only thing that happens is that new backups and chatlogs are created.

If you try to backup the ForgeEssentials directory, it's basically as if you backup a backup which is why I said it is not necessary. I should have explained that a bit more above.
