### ISSUE TITLE
I am trying to disable access to gamemode 1 from other players, not working.

### ISSUE THREAD

**Issue by rodnico2681** [ForgeEssentials/ForgeEssentialsMain#1654]
Hello, I have tried all kind of permissions to disable, god and gamemode so that the players in my server wont have access to these commands, after several attempts they still seem to have it, nothing that I have tried is working, please help.

**Comment by liach** [comment]
Have you updated to the newest beta version? It's fixed in #1650.

**Comment by rodnico2681** [comment]
let me check, and what would be the command to disable btw, just to be sure I am doing it right.

**Comment by rodnico2681** [comment]
yea, I must be writing it wrong or something, not even putting the players in the bubble group disables it like it used to when I first started the server.

**Comment by olee** [comment]
If you are on 1.8, the fix for permissions was not merged yet.
If you are on 1.7.10, permissions should work after updating to latest build.

**Comment by rodnico2681** [comment]
alright, thank you olee.

**Comment by olee** [comment]
Actually I forgot I merged it already about 24h ago - If you update to latest it should work properly.

**Comment by olee** [comment]
Ok it seems the "fix" got it working in dev environment, but it does not work on an actual server yet.
Continues in #1650

**Comment by rodnico2681** [comment]
yea, I just recently put in the new updated version and the gamemode and fly cant seem to be disabled, althought the /god now can be, Great Job on that one, just keep me posted on how you do with the other two, it could also be they way i'm trying to disable it, I type for instance /p user brod deny fe.protection.gamemode.* I also tried to assigned the value this way /p user brod deny fe.protection.gamemode.1.*  i'm trying to disable the /gamemode 1 command the players in my server.

**Comment by olee** [comment]
The issue has been fixed in https://github.com/ForgeEssentials/ForgeEssentialsMain/commit/c4f41681a4c419482a2e8efdb7667c054b4c4c17 so this is no longer an issue.

As for these permissions you tried to configure:
**Read the tutorial on the wiki and the [PermissionList.txt](https://github.com/ForgeEssentials/ForgeEssentialsMain/wiki/PermissionList.txt)**.
If you read that, you should notice that denying `fe.protection.gamemode.*` is completely useless.
The bug with permissions has been fixed now and it is probably best if you delete the permissions you configured trying to fix that (by deleting permissions folder). If you are not sure about what permissions to configure, always check that file and there should be no problem.

**Comment by rodnico2681** [comment]
thank you olee, I will delete the file and try over, I did notice there is no permission for fly or kit's anymore.
