### ISSUE TITLE
AFK AutoKick

### ISSUE THREAD

**Issue by LordIconMC** [ForgeEssentials/ForgeEssentialsMain#1672]
Enhancement 
When setting a group or user with allow * (for my example i tested with _OPS_ group)
AFK will be set auto kick.

if Allow * is set it should allow afk 

It does this because AFK.autokick gets set to true

**Comment by LordIconMC** [comment]
Enhancement*

**Comment by olee** [comment]
Generally just setting `* = true` is not advised and we cannot support this.
(However I still wonder if there is a good way to solve this).

You should instead only allow sub-groups of permissions like `fe.protection.break.* = true`.

@luacs1998 Though I think we need to get the auto-kick permission out of `fe.commands.afk`, so it does not get affected by `fe.commands.* = true` for example. This can be really annoying otherwise.

**Comment by LordIconMC** [comment]
If this is not the supported way to set all permissions to ops then should I set all permission for op group manually? Thanks for the feedback

**Comment by olee** [comment]
What you can easily do is "extending" the OPs group and remove the permissions you do not want.
This should do it: `/p group myOps parent add _OPS_`
