### ISSUE TITLE
Fake Player Support

### ISSUE THREAD

**Issue by mzx987** [ForgeEssentials/ForgeEssentialsMain#1683]
Things from mods like OpenComputers or Computercraft have robots or turtles in them. I've done a bit of testing and noticed that they can bypass protected buildings by breaking blocks.

Is it possible to add support to also check for fake players, or am I missing something else?

EDIT: Altering "fe.protection.*" in group _FAKEPLAYERS_ wiped my inventory whenever I entered any zone. Not sure what that's all about...
EDIT 2: Turns out my fe.internal.group was _FAKEPLAYERS_ for some weird reason.

**Comment by OvermindDL1** [comment]
I do not think those are fake players in those mods but rather just call the usual internal calls.

**Comment by olee** [comment]
As far as I know OpenComputers at last was programmed properly and uses FakePlayers.
Also you should not just do `fe.protection.* = false` because it will also deny item permissions (which will delete items).

However it's still a bug that your own player was considered a fakeplayer.
This is because once a real player was used once as a fakeplayer, he is after that always considered a fakeplayer.

**Comment by olee** [comment]
Fixed in https://github.com/ForgeEssentials/ForgeEssentialsMain/commit/be9fd82a1f6ee6e4b871c3ee1b99c362ef096f04
