### ISSUE TITLE
Paidcommand and Permissions

### ISSUE THREAD

**Issue by Centanoul** [ForgeEssentials/ForgeEssentialsMain#1703]
Having an issue with paidcommand not activating /give unless the player has command.give=true.

![command1](https://cloud.githubusercontent.com/assets/4166871/9344379/1ea933b6-45bd-11e5-9e42-fdf10777c64c.png)
![command2](https://cloud.githubusercontent.com/assets/4166871/9344386/2a717c44-45bd-11e5-87bf-20970d68d603.png)

**Comment by olee** [comment]
Oh... interesting this was not noticed before...
Will be checked and fixed ASAP.

**Comment by olee** [comment]
Fixed by https://github.com/ForgeEssentials/ForgeEssentialsMain/commit/1c064551b492706e17953cbe881b765d456bddb8

FE now has new special system users which are used for some actions.
Command blocks in general will use the `$COMMANDBLOCK` user, and economy will use the `$FE_ECONOMY` user for commands like `/paidcommand` and `/sellcommand`.
By default this user has only the default guest permissions and additionaly **only** the `command.give` permission. This greatly helps increasing the security of using command blocks.

PS @luacs1998 we need a permission to allow editing command blocks. By default only OPs can edit them right?

**Comment by olee** [comment]
@Centanoul I highly recommend you update to build 887 as it adds a very important permission check for command blocks which was broken before.
