### ISSUE TITLE
Difficulty with PlayerLogger

### ISSUE THREAD

**Issue by DoxProx** [ForgeEssentials/ForgeEssentialsMain#1707]
I am running 1.8 forgeessentials-1.8-1.8.0.26-server. Maybe I don't quite understand PlayerLogger, however the description is "The Playerlogger module logs every player interaction with your server and provides you with powerful tools to check these logs. Someone stole another player’s diamonds from his chest? No problem! Check the access log to the chest and find out who was the culprit!" So I tried it out using the clock and left click stuff, and the log showed nothing despite the fact that the block had been placed very recently. Another issue is that I can't find a way to access any logs from it, however the're may not be any. My last question is about the /whisper command. I know it doesn't seem relevant but I figured "every player interaction with your server" included whispers, which was the main reason I looked into it. A little side question, is there any way to view whispers/messages?

**Comment by olee** [comment]
Private messages will never be logged. This is a severe violation of privacy! (That you even think of that...).

About the playerlogger checking:
There was a bug in the clock tool, making it impossible to get the correct logs.
This is fixed now and you should be able to check your logs with that now.

About chests, there are two thing you should consider:
1. If it is a double chest, you will have to check both blocks of the chest
  (Because the chest consists of two blocks and only the interaction with the clicked block is logged)
3. Only interactions with the block itself are logged yet. Actually removing items etc. is not logged yet. This is because forge does not provide any events for inventory interactions and we are still trying to figure out a way to do this (I will try to fix this as part of this issue)

**Comment by olee** [comment]
PS: This fix was only applied to 1.7.10 branch yet.
Please wait a little while until I can merge all recent changes from 1.7.10 to 1.8 again.

**Comment by olee** [comment]
Changes have been merged now.
Get latest build from http://ci.forgeessentials.com/job/FE-1.8/
