### ISSUE TITLE
How to connect to playerlogger

### ISSUE THREAD

**Issue by Icepick869** [ForgeEssentials/ForgeEssentialsMain#1714]
I have been trying to access the playerlogger and the first problem is that I'm not even sure it is set up correctly. Second is I am not sure how I'm supposed to connect.

The Forge Minecraft server is on a Linux machine and I am trying to access from a Windows machine. Without changing the default config I have been trying to open the playerlogger with the "http://<ipaddress>:3306/forgeessentials/playerlogger" and get unable to connect.

The only tutorial I've found is based on the Bukkit plugin and the wiki has very limited information.

**Comment by olee** [comment]
@Icepick869 Next time you ask on IRC, wait a little to give us time to answer :smile: 

As for playerlogger in general - there is no way to access the default database while the server is running. This is because the DB is running in embedded mode which greatly boosts the performance, but requires locking the DB file. However there are other ways to access the logged data.
If you want you can come on IRC and I can help you :wink:

**Comment by luacs1998** [comment]
Do we close this?

**Comment by Icepick869** [comment]
I haven't managed to reach the IRC yet, but please go ahead and close it as I will when I can and I'm sure that will gt things resolved.

**Comment by olee** [comment]
Ok sounds good.

**Comment by Icepick869** [comment]
I waited through 3 chapters of Heinlein.

**Comment by olee** [comment]
Playerlogger can only be accessed directly through the MC server.
The database runs in embedded mode for performance reasons and so you can only use ingame commands and remote to query it (where I think remote is not done yet for playerlogger).
