### ISSUE TITLE
Shop Feature 

### ISSUE THREAD

**Issue by paintballlaws** [ForgeEssentials/ForgeEssentialsMain#1748]
Adding the ability todo shop commands via signs because the command block commands allow other players to steal money and or items

**Comment by olee** [comment]
You **can't** steal money.
The only thing that could happen is that when someone pushes the button, the command could be run for another player. But that player would still get the items / the money of the trade and no one else.

But instead of only signs I had another nice idea:
![ydgn6](https://cloud.githubusercontent.com/assets/6547794/9826428/32d0a642-5915-11e5-976e-b68b8bfcfd98.png)

The item which can be bought/sold could be grabbed from an adjacent item frame.
Normal right click would be buying and maybe clicking with the same item (or maybe sneak clicking) would sell it.

**Comment by AnrDaemon** [comment]
There's no need for "buying or selling". I can't imagine a situation, in which I would buy AND sell the same item. Even if I do. What stops me from posting two signs? One for buying. One for selling.
So, the setting sign can be something like this:
```
[shop]
buy 20
for 5
```

And an active sign would list something like
```
<Playername>
buys/sells XX/YY
price ZZ
```

P.S.
And sneak-click to sell or buy whole stack or what is left.

**Comment by paintballlaws** [comment]
I agree with you guys I like the sigh feature i don't know that I would like buying and selling to be in the same sign but also when selling things it should take whatever amount you have and sell that instead of wanting a whole stack or whatever is put into the command as a number

**Comment by AnrDaemon** [comment]
p> when selling things it should take whatever amount you have and sell that
p> instead of wanting a whole stack or whatever is put into the command as a number

That's not your word to say.
I am selling, I want to control, how much I want to sell.
Or we get SoH model of "an apple, a coin and a grudge against me".

**Comment by olee** [comment]
By default it should only 1 item I think... or all when the player has it in his hand only?
Anyway about the signs - I think like that it should work:

Sell for 15, buy for 20 each item
````
[shop]
buy 20
sell 15
````

Sell for 2, buy for 2every 64 items (e.g., dirt)
````
[shop]
buy 6
sell 5
amount 64
````

Buy only for 20 (iron?)
````
[shop]
buy 20
````

**Comment by AnrDaemon** [comment]
BZ> By default it should only 1 item I think... or all when the player has it in his hand only?

One item (when buying).
And may be what player is holding in the hand (when selling).

BZ> Anyway about the signs - I think like that it should work:
BZ> Sell for 15, buy for 20 each item

BZ> [shop]
BZ> buy 20
BZ> sell 15

Is that "buy 20" or "buy for 20" ? Same for sell?
If that's price, what is the amount?

BZ> Sell for 2, buy for 2every 64 items (e.g., dirt)
BZ> [shop]
BZ> buy 6
BZ> sell 5
BZ> amount 64

So, buy AND sell 64 items? So that it will never complete?

BZ> Buy only for 20 (iron?)
BZ> [shop]
BZ> buy 20

for? So, it is price? Then, what is the amount?
Sorry, but aside being confusing, it makes very little sense.
Keep it simple and stupid.

```
[shop]
buy|sell <amount>
for <price>

**Comment by paintballlaws** [comment]
For these examples how do you know what your buying or selling since your using all four lines for buy and sell but not telling the comma and what it is that your buying and selling and also how would and admin shop work instead of having [shop] could we just do [adminshop] or something to that effect? Idk just a thought

**Comment by olee** [comment]
First: Wth should an "adminshop" be?

@AnrDaemon the syntax was just shortened, but it meant "buy for" and "sell for".
I could also allow this syntax (i.e. make the "for" optional if there is enough space):
````
[shop]
buy for 6
sell for 5
````

By default it would always buy / sell only one item. Only if the `amount <x>` is added, it would sell more than one item at once (i.e. like selling 64 dirt gives only 1 coin).

@paintballlaws And the item will not be on the sign - if we would do that the item name would in most cases already cover over 50% of the available text space. Instead there will be an adjancent item frame with the item in it. This also allows to exactly configure the state like enchantments and other metadata on the item. Take a look at [this image here](#issuecomment-139662664)

**Comment by paintballlaws** [comment]
An admin shop meaning just like the command for command blocks now to where it dosent need a player wallet to give and receive items from players an ahh i see my bad yeah i like the item frame idea

**Comment by olee** [comment]
@AnrDaemon do you get what @paintballlaws described?
(Sorry with that english it's a bit too hard for me understand)

**Comment by paintballlaws** [comment]
um let me see if i can clear it up, I want to be able to use [AdminShop] or whatever name you you think would be better on a sign and have it work like the /paidcommand and or the /sellcommand insted of having to use command blocks. hopefully that makes more sense

**Comment by AnrDaemon** [comment]
In case of admin shop, I see why you are not specifying amount (supposedly, admin coffers are bottomless).
But in case of player-run auctions, both price and amount needs to be able to be specified. In one way or another.
And I still think that using a sign for only one action wil be more manageable.

Though, since we've reached the point of understanding, I'll leave the implementation details up to you :)

**Comment by olee** [comment]
Implemented in https://github.com/ForgeEssentials/ForgeEssentialsMain/commit/ecffb56230caea9ba6254f6e295c47be22decee5

Wiki article following soon (hopefully...)

**Comment by olee** [comment]
https://github.com/ForgeEssentials/ForgeEssentialsMain/wiki/Shops

**Comment by Zethalion** [comment]
When a shop is made this way, is there a check the player who makes the sing is an op so regular players cannot create cheap shops for themselves?

**Comment by AnrDaemon** [comment]
The shop can be created but can not be activated by a player without sufficient privileges.
An operator or someone else with sufficient privileges must activate the shop (by right-clicking the sign).

**Comment by olee** [comment]
Thanks for providing the info @AnrDaemon 
I better clarify this in the wiki (if it really was not in it already)
