### ISSUE TITLE
Mod Compatibility - SFM/BC/others

### ISSUE THREAD

**Issue by Sakata-MC** [ForgeEssentials/ForgeEssentialsMain#1759]
We've been having issues with Steve's factory manager, buildcraft, and a few other mods here and there. The issue is that they cannot break/place blocks.
The quarry and filler do not work at all, and SFM cannot use the gates to break/place block either.

They do not seem to have Fake-players explicitly defined. We've tried adding them manually using any names we could find for the fake-players on-line to no avail.

**Comment by luacs1998** [comment]
Fakeplayer names should be the same as MCPC's - as I said in IRC, the mods decide their own fakeplayer names, we just get the list from Forge (which should be the same as MCPC.

To get this list, run `/p group _FAKEPLAYERS_ users`

**Comment by olee** [comment]
Sadly the `/p group _FAKEPLAYERS_ users` thing does not work any more, because fakeplayers are not added to that group permanently any more. This had to be done because sometimes you have FakePlayers for users who are offline / somewhere else in the world. Adding them permanently would break that player's permission. 

There was actually a bug that was fixed in https://github.com/ForgeEssentials/ForgeEssentialsMain/commit/6e6f95a43e7a2b014d5431d540acb0b754017c27
